/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    PickLang: typeof import('./src/components/PickLang.vue')['default']
    PiniaDemoOptionControl: typeof import('./src/components/PiniaDemo/OptionControl.vue')['default']
    PiniaDemoOptionInfo: typeof import('./src/components/PiniaDemo/OptionInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoListTodoContent: typeof import('./src/components/TodoList/TodoContent.vue')['default']
    TodoListTodoFooter: typeof import('./src/components/TodoList/TodoFooter.vue')['default']
    TodoListTodoHeader: typeof import('./src/components/TodoList/TodoHeader.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
