version: '3.8'
services:
  web:
    build: .
    image: vue3-todo-list:latest # 为镜像指定一个名称
    ports:
      - "3102:3102"
    volumes:
      - .:/app
      - /app/node_modules # 这将忽略宿主机的 node_modules 目录，使用容器内的 node_modules
    command: npm run dev
