name: Deploy to VPS

on:
  push:
    branches:
      - master # 或是你用於部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.VPS_IP }}" >> ~/.ssh/known_hosts

      - name: Get latest commit message
        id: get_commit
        run: echo "COMMIT_MSG=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
        shell: bash
        continue-on-error: false

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa root@"${{ secrets.VPS_IP }}" "
            cd '${{ secrets.REPO_DIR_PATH }}' &&
            git pull --rebase --autostash &&
            git checkout -- . &&
            docker-compose -f docker-compose.prod.yml up -d --build
          "

      - name: Call TG Bot
        env:
          COMMIT_MSG: ${{ env.COMMIT_MSG }}
        run: |
          curl -X POST \
          -H 'Content-Type: application/json' \
          -d "{\"chat_id\": \"${{ secrets.TG_CHAT_ID }}\", \"text\": \"部屬 \\nhttp://todolist.jimmy512.com \\n已經成功\\nCommit Message: \\n${COMMIT_MSG}\", \"disable_notification\": false}" \
          https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage
